baseURL = "https://utsavgupta.in/"
languageCode = "en-us"
title = "Utsav Gupta"
paginate = 5
pygmentsUseClasses = true

[permalinks]
	posts = "/blog/:slug/"

[params]
    mainSections = ["posts"]
    logo = "/img/logo.svg"
    author = "Utsav Gupta"

[params.social]
    email = "mail@utsavgupta.in"
    github = "utsavgupta"
    linkedin = "in/utsav-gupta"
    stackoverflow = "users/520209/utsav"
    flickr = "photos/193395831@N04/"
    public_key = "/public_key.txt"


[params.colors.light]
    text = "black"
    background = "white"
    primary = "#5452BB"
    secondary = "#C680C3"

[params.colors.dark]
    text = "#fff"
    background = "#040d21"
    primary = "#00C9FF"
    secondary = "#92FE9D"

[markup.goldmark.renderer] 
    unsafe= true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = ""
    tabWidth = 4