baseURL = "/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Utsav Gupta"
theme = "hugo-goa"
# enableGitInfo = true
pygmentsCodefences  = true
pygmentsUseClasses  = true
# hasCJKLanguage = true  # If Chinese/Japanese/Korean is your main content language, enable this to make wordCount works right.
rssLimit = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.
enableEmoji = true  # Shorthand emojis in content files - https://gohugo.io/functions/emojify/
# googleAnalytics = "UA-123-45"
# disqusShortname = "yourdiscussshortname"

[author]
  name = "Utsav Gupta"

## Site Settings
[params]
author = "Utsav Gupta"
intro = "Your average software guy"
description = "Aspiring cloud architect. Amateur photographer. INTJ."
authorimage = "headshot.jfif"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Simple minimalist theme"
keywords = "minimalist,blog,goa,hugo,developer"

## Social Accounts
[params.social]
github = "utsavgupta"
#instagram = "<username>"
#xing = "<username>"
linkedin = "utsav-gupta"
#twitter = "<username>"
#facebook = "<username>"
#google = "<username>"
#googlescholar = "<account_id>"
stackoverflow = "520209/utsav"
#lastfm = "<username>"
#goodreads = "<username>"
#gitlab = "<username>"
#bitbucket = "<username>"
fivehundredpx = "utsavgupta89"
#flickr = "<username>"
#foursquare = "<username>"
#hackernews = "<username>"
#kickstarter = "<username>"
#patreon = "<username>"
#pintrest = "<username>"
#steam = "<username>"
#reddit = "<username>"
#snapchat = "<username>"
#youtube = "<channelid>"
#keybase = "<username>"
#twitch = "<username>"
#soundcloud = "<username>"
#tumblr = "<username>"
#strava = "<username>"
#skype = "<username>"
#telegram = "<username>"
#whatsapp = "<username>"
email = "mail@utsavgupta.in"
pgp = "public_key"

## Extras
[params.extra]
copyright = "Â© 2020. Utsav Gupta. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
poweredby = true
highlightjs = true
socialmarkup = true
toc = true
displayrssicon = true

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
